# Generated by Django 5.1.4 on 2025-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_college_course_faculty_marksheet_student_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('appoinmentDate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('illness', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_client',
            },
        ),
    ]
