# Generated by Django 5.1.4 on 2025-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalQuantity', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('orderDate', models.DateField()),
                ('totalCost', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'sos_purchaseorder',
            },
        ),
    ]
