# Generated by Django 5.1.4 on 2025-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=15)),
                ('importance', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_Customer',
            },
        ),
    ]
